#define ONE_WIRE_BUS 2
#define NUM_THERMOCOUPLES 6
#define OUTPUT_PIN 3
#define SERIAL_BAUDRATE 9600
#define DEBOUNCE_LOOPS 5

#define MIN_LEGAL_TEMP_C -20
#define MAX_LEGAL_TEMP_C 150

typedef float tempCArray[NUM_THERMOCOUPLES];